
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl telemetryMessageCommon
// ------------------------------
#ifndef TELEMETRYMESSAGECOMMON_EXPORT_H
#define TELEMETRYMESSAGECOMMON_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TELEMETRYMESSAGECOMMON_HAS_DLL)
#  define TELEMETRYMESSAGECOMMON_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TELEMETRYMESSAGECOMMON_HAS_DLL */

#if !defined (TELEMETRYMESSAGECOMMON_HAS_DLL)
#  define TELEMETRYMESSAGECOMMON_HAS_DLL 1
#endif /* ! TELEMETRYMESSAGECOMMON_HAS_DLL */

#if defined (TELEMETRYMESSAGECOMMON_HAS_DLL) && (TELEMETRYMESSAGECOMMON_HAS_DLL == 1)
#  if defined (TELEMETRYMESSAGECOMMON_BUILD_DLL)
#    define telemetryMessageCommon_Export ACE_Proper_Export_Flag
#    define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TELEMETRYMESSAGECOMMON_BUILD_DLL */
#    define telemetryMessageCommon_Export ACE_Proper_Import_Flag
#    define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TELEMETRYMESSAGECOMMON_BUILD_DLL */
#else /* TELEMETRYMESSAGECOMMON_HAS_DLL == 1 */
#  define telemetryMessageCommon_Export
#  define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARATION(T)
#  define TELEMETRYMESSAGECOMMON_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TELEMETRYMESSAGECOMMON_HAS_DLL == 1 */

// Set TELEMETRYMESSAGECOMMON_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (TELEMETRYMESSAGECOMMON_NTRACE)
#  if (ACE_NTRACE == 1)
#    define TELEMETRYMESSAGECOMMON_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define TELEMETRYMESSAGECOMMON_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !TELEMETRYMESSAGECOMMON_NTRACE */

#if (TELEMETRYMESSAGECOMMON_NTRACE == 1)
#  define TELEMETRYMESSAGECOMMON_TRACE(X)
#else /* (TELEMETRYMESSAGECOMMON_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define TELEMETRYMESSAGECOMMON_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (TELEMETRYMESSAGECOMMON_NTRACE == 1) */

#endif /* TELEMETRYMESSAGECOMMON_EXPORT_H */

// End of auto generated file.
